/* compile_test.c generated by valac 0.14.2, the Vala compiler
 * generated from compile_test.vala, do not modify */

/*define our namespace*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define COMPILE_TEST_TYPE_COMPILE_TEST (compile_test_compile_test_get_type ())
#define COMPILE_TEST_COMPILE_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COMPILE_TEST_TYPE_COMPILE_TEST, compile_testCompileTest))
#define COMPILE_TEST_COMPILE_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), COMPILE_TEST_TYPE_COMPILE_TEST, compile_testCompileTestClass))
#define COMPILE_TEST_IS_COMPILE_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COMPILE_TEST_TYPE_COMPILE_TEST))
#define COMPILE_TEST_IS_COMPILE_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), COMPILE_TEST_TYPE_COMPILE_TEST))
#define COMPILE_TEST_COMPILE_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), COMPILE_TEST_TYPE_COMPILE_TEST, compile_testCompileTestClass))

typedef struct _compile_testCompileTest compile_testCompileTest;
typedef struct _compile_testCompileTestClass compile_testCompileTestClass;
typedef struct _compile_testCompileTestPrivate compile_testCompileTestPrivate;

struct _compile_testCompileTest {
	GObject parent_instance;
	compile_testCompileTestPrivate * priv;
};

struct _compile_testCompileTestClass {
	GObjectClass parent_class;
};


static gpointer compile_test_compile_test_parent_class = NULL;

GType compile_test_compile_test_get_type (void) G_GNUC_CONST;
enum  {
	COMPILE_TEST_COMPILE_TEST_DUMMY_PROPERTY
};
gint compile_test_compile_test_main (gchar** args, int args_length1);
compile_testCompileTest* compile_test_compile_test_new (void);
compile_testCompileTest* compile_test_compile_test_construct (GType object_type);


/**
 * The main method that is invoked when this program is run.
 *
 * @param args command line arguments
 */
gint compile_test_compile_test_main (gchar** args, int args_length1) {
	gint result = 0;
	FILE* _tmp0_;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "I have been successfully compiled and run.\n");
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return compile_test_compile_test_main (argv, argc);
}


compile_testCompileTest* compile_test_compile_test_construct (GType object_type) {
	compile_testCompileTest * self = NULL;
	self = (compile_testCompileTest*) g_object_new (object_type, NULL);
	return self;
}


compile_testCompileTest* compile_test_compile_test_new (void) {
	return compile_test_compile_test_construct (COMPILE_TEST_TYPE_COMPILE_TEST);
}


static void compile_test_compile_test_class_init (compile_testCompileTestClass * klass) {
	compile_test_compile_test_parent_class = g_type_class_peek_parent (klass);
}


static void compile_test_compile_test_instance_init (compile_testCompileTest * self) {
}


/**
 * Example class showing Vala syntax and serving as an compile test.
 *
 * This class named CompileTest is inherited from the Object from GLib.
 */
GType compile_test_compile_test_get_type (void) {
	static volatile gsize compile_test_compile_test_type_id__volatile = 0;
	if (g_once_init_enter (&compile_test_compile_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (compile_testCompileTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) compile_test_compile_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (compile_testCompileTest), 0, (GInstanceInitFunc) compile_test_compile_test_instance_init, NULL };
		GType compile_test_compile_test_type_id;
		compile_test_compile_test_type_id = g_type_register_static (G_TYPE_OBJECT, "compile_testCompileTest", &g_define_type_info, 0);
		g_once_init_leave (&compile_test_compile_test_type_id__volatile, compile_test_compile_test_type_id);
	}
	return compile_test_compile_test_type_id__volatile;
}



